name: Build Container Image on Release
on:
  release:
    types: [published]

env:
  IMAGE_URL: ${{ vars.CONTAINER_REGISTRY }}/${{ github.repository }}
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      PRIMARY_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      BACKUP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: build and tag image
        run: |
          docker build . --tag $IMAGE_URL:$VERSION --quiet
          docker image tag $IMAGE_URL:$VERSION $IMAGE_URL:latest

      - name: log in to registry
        run: echo "${PRIMARY_TOKEN:-$BACKUP_TOKEN}" | docker login ${{ vars.CONTAINER_REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      - name: deploy
        run: |
          docker push $IMAGE_URL:$VERSION --quiet
          docker push $IMAGE_URL:latest --quiet
